INSERT INTO public.dimensao_produto (produto) VALUES
	 ('7up Diet,355 Ml'),
	 ('Absolut Citron'),
	 ('Alize Red Passion'),
	 ('Alize Sunset'),
	 ('Allspice - Jamaican'),
	 ('Almonds Ground Blanched'),
	 ('Amaretto'),
	 ('Amarula Cream'),
	 ('Anchovy Fillets'),
	 ('Anchovy In Oil');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Anchovy Paste - 56 G Tube'),
	 ('Anisette - Mcguiness'),
	 ('Appetiser - Bought'),
	 ('Appetizer - Asian Shrimp Roll'),
	 ('Appetizer - Assorted Box'),
	 ('Appetizer - Cheese Bites'),
	 ('Appetizer - Chicken Satay'),
	 ('Appetizer - Escargot Puff'),
	 ('Appetizer - Lobster Phyllo Roll'),
	 ('Appetizer - Mini Egg Roll,Shrimp');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Appetizer - Mushroom Tart'),
	 ('Appetizer - Sausage Rolls'),
	 ('Appetizer - Seafood Assortment'),
	 ('Appetizer - Shrimp Puff'),
	 ('Appetizer - Spring Roll,Veg'),
	 ('Appetizer - Tarragon Chicken'),
	 ('Appetizer - Veg Assortment'),
	 ('Apple - Custard'),
	 ('Apple - Delicious,Golden'),
	 ('Apple - Delicious,Red');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Apple - Fuji'),
	 ('Apple - Granny Smith'),
	 ('Apple - Macintosh'),
	 ('Apple - Royal Gala'),
	 ('Apples - Sliced / Wedge'),
	 ('Apples - Spartan'),
	 ('Apricots - Dried'),
	 ('Apricots - Halves'),
	 ('Apricots Fresh'),
	 ('Apron');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Arctic Char - Fillets'),
	 ('Arctic Char - Fresh,Whole'),
	 ('Arizona - Green Tea'),
	 ('Arizona - Plum Green Tea'),
	 ('Aromat Spice / Seasoning'),
	 ('Arrowroot'),
	 ('Artichoke - Bottom,Canned'),
	 ('Artichoke - Fresh'),
	 ('Artichoke - Hearts,Canned'),
	 ('Artichokes - Jerusalem');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Artichokes - Knobless,White'),
	 ('Asparagus - Frozen'),
	 ('Asparagus - Green,Fresh'),
	 ('Asparagus - Mexican'),
	 ('Aspic - Amber'),
	 ('Aspic - Clear'),
	 ('Aspic - Light'),
	 ('Assorted Desserts'),
	 ('Avocado'),
	 ('Bacardi Breezer - Strawberry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bacardi Breezer - Tropical'),
	 ('Bacardi Mojito'),
	 ('Bacardi Raspberry'),
	 ('Bacon Strip Precooked'),
	 ('Bag - Bread,White,Plain'),
	 ('Bag - Clear 7 Lb'),
	 ('Bag Clear 10 Lb'),
	 ('Bagel - Ched Chs Presliced'),
	 ('Bagel - Everything Presliced'),
	 ('Bagel - Plain');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bagel - Sesame Seed Presliced'),
	 ('Bagel - Whole White Sesame'),
	 ('Bagelers'),
	 ('Bagelers - Cinn / Brown'),
	 ('Bagelers - Cinn / Brown Sugar'),
	 ('Bagels Poppyseed'),
	 ('Baking Powder'),
	 ('Baking Soda'),
	 ('Bamboo Shoots - Sliced'),
	 ('Banana');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Banana - Leaves'),
	 ('Banana Turning'),
	 ('Bananas'),
	 ('Bandage - Finger Cots'),
	 ('Bandage - Flexible Neon'),
	 ('Bar - Granola Trail Mix Fruit Nut'),
	 ('Bar - Sweet And Salty Chocolate'),
	 ('Bar Bran Honey Nut'),
	 ('Bar Energy Chocchip'),
	 ('Bar Mix - Lemon');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bar Mix - Lime'),
	 ('Bar Mix - Pina Colada,355 Ml'),
	 ('Bar Nature Valley'),
	 ('Barley - Pearl'),
	 ('Basil - Dry,Rubbed'),
	 ('Basil - Fresh'),
	 ('Basil - Thai'),
	 ('Bay Leaf'),
	 ('Bay Leaf Fresh'),
	 ('Bay Leaf Ground');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beans - Black Bean,Canned'),
	 ('Beans - Black Bean,Dry'),
	 ('Beans - Black Bean,Preserved'),
	 ('Beans - Butter Lrg Lima'),
	 ('Beans - Fava Fresh'),
	 ('Beans - Fava,Canned'),
	 ('Beans - Fine'),
	 ('Beans - French'),
	 ('Beans - Green'),
	 ('Beans - Kidney White');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beans - Kidney,Canned'),
	 ('Beans - Kidney,Red Dry'),
	 ('Beans - Long,Chinese'),
	 ('Beans - Navy,Dry'),
	 ('Beans - Soya Bean'),
	 ('Beans - Turtle,Black,Dry'),
	 ('Beans - Wax'),
	 ('Beef - Baby,Liver'),
	 ('Beef - Bones,Cut - Up'),
	 ('Beef - Bones,Marrow');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beef - Chuck,Boneless'),
	 ('Beef - Cooked,Corned'),
	 ('Beef - Cow Feet Split'),
	 ('Beef - Diced'),
	 ('Beef - Eye Of Round'),
	 ('Beef - Flank Steak'),
	 ('Beef - Ground Lean Fresh'),
	 ('Beef - Ground Medium'),
	 ('Beef - Ground,Extra Lean,Fresh'),
	 ('Beef - Inside Round');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beef - Kindney,Whole'),
	 ('Beef - Kobe Striploin'),
	 ('Beef - Montreal Smoked Brisket'),
	 ('Beef - Outside,Round'),
	 ('Beef - Ox Tail,Frozen'),
	 ('Beef - Ox Tongue'),
	 ('Beef - Ox Tongue,Pickled'),
	 ('Beef - Prime Rib Aaa'),
	 ('Beef - Rib Roast,Cap On'),
	 ('Beef - Rib Roast,Capless');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beef - Roasted,Cooked'),
	 ('Beef - Rouladin,Sliced'),
	 ('Beef - Salted'),
	 ('Beef - Shank'),
	 ('Beef - Short Loin'),
	 ('Beef - Short Ribs'),
	 ('Beef - Striploin'),
	 ('Beef - Striploin Aa'),
	 ('Beef - Sushi Flat Iron Steak'),
	 ('Beef - Tender Tips');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beef - Tenderloin'),
	 ('Beef - Tenderloin - Aa'),
	 ('Beef - Texas Style Burger'),
	 ('Beef - Tongue,Fresh'),
	 ('Beef - Top Butt'),
	 ('Beef - Top Butt Aaa'),
	 ('Beef - Top Sirloin'),
	 ('Beef Cheek Fresh'),
	 ('Beef Dry Aged Tenderloin Aaa'),
	 ('Beef Flat Iron Steak');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beef Ground Medium'),
	 ('Beef Striploin Aaa'),
	 ('Beer - Alexander Kieths,Pale Ale'),
	 ('Beer - Blue'),
	 ('Beer - Blue Light'),
	 ('Beer - Camerons Auburn'),
	 ('Beer - Camerons Cream Ale'),
	 ('Beer - Corona'),
	 ('Beer - Fruli'),
	 ('Beer - Guiness');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beer - Heinekin'),
	 ('Beer - Labatt Blue'),
	 ('Beer - Maudite'),
	 ('Beer - Mcauslan Apricot'),
	 ('Beer - Mill St Organic'),
	 ('Beer - Molson Excel'),
	 ('Beer - Moosehead'),
	 ('Beer - Muskoka Cream Ale'),
	 ('Beer - Original Organic Lager'),
	 ('Beer - Paulaner Hefeweisse');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beer - Pilsner Urquell'),
	 ('Beer - Rickards Red'),
	 ('Beer - Sleeman Fine Porter'),
	 ('Beer - Sleemans Cream Ale'),
	 ('Beer - Sleemans Honey Brown'),
	 ('Beer - Steamwhistle'),
	 ('Beer - Tetleys'),
	 ('Beer - True North Strong Ale'),
	 ('Beer - Upper Canada Lager'),
	 ('Beer - Upper Canada Light');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Beets'),
	 ('Beets - Golden'),
	 ('Beets - Mini Golden'),
	 ('Blackberries'),
	 ('Blouse / Shirt / Sweater'),
	 ('Blue Curacao - Marie Brizard'),
	 ('Blueberries'),
	 ('Blueberries - Frozen'),
	 ('Bols Melon Liqueur'),
	 ('Bonito Flakes - Toku Katsuo');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Boogies'),
	 ('Bouillion - Fish'),
	 ('Bowl 12 Oz - Showcase 92012'),
	 ('Brandy - Bar'),
	 ('Brandy - Orange,Mc Guiness'),
	 ('Brandy Apricot'),
	 ('Brandy Cherry - Mcguinness'),
	 ('Bread - 10 Grain'),
	 ('Bread - 10 Grain Parisian'),
	 ('Bread - Assorted Rolls');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - Bagels,Mini'),
	 ('Bread - Bagels,Plain'),
	 ('Bread - Bistro Sour'),
	 ('Bread - Bistro White'),
	 ('Bread - Burger'),
	 ('Bread - Calabrese Baguette'),
	 ('Bread - Ciabatta Buns'),
	 ('Bread - Corn Muffaleta Onion'),
	 ('Bread - Corn Muffaletta'),
	 ('Bread - Crumbs,Bulk');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - Dark Rye'),
	 ('Bread - Dark Rye,Loaf'),
	 ('Bread - English Muffin'),
	 ('Bread - Flat Bread'),
	 ('Bread - French Baquette'),
	 ('Bread - French Stick'),
	 ('Bread - Frozen Basket Variety'),
	 ('Bread - Granary Small Pull'),
	 ('Bread - Hamburger Buns'),
	 ('Bread - Italian Roll With Herbs');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - Italian Sesame Poly'),
	 ('Bread - Kimel Stick Poly'),
	 ('Bread - Malt'),
	 ('Bread - Mini Hamburger Bun'),
	 ('Bread - Multigrain'),
	 ('Bread - Multigrain Oval'),
	 ('Bread - Multigrain,Loaf'),
	 ('Bread - Olive'),
	 ('Bread - Onion Focaccia'),
	 ('Bread - Pain Au Liat X12');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - Petit Baguette'),
	 ('Bread - Pita'),
	 ('Bread - Pullman,Sliced'),
	 ('Bread - Pumpernickel'),
	 ('Bread - Raisin'),
	 ('Bread - Raisin Walnut Pull'),
	 ('Bread - Roll,Canadian Dinner'),
	 ('Bread - Roll,Italian'),
	 ('Bread - Roll,Soft White Round'),
	 ('Bread - Roll,Whole Wheat');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - Rolls,Corn'),
	 ('Bread - Rolls,Rye'),
	 ('Bread - Rosemary Focaccia'),
	 ('Bread - Rye'),
	 ('Bread - Sour Batard'),
	 ('Bread - Sour Sticks With Onion'),
	 ('Bread - Sticks,Thin,Plain'),
	 ('Bread - Wheat Baguette'),
	 ('Bread - White Epi Baguette'),
	 ('Bread - White Mini Epi');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread - White,Sliced'),
	 ('Bread Base - Gold Formel'),
	 ('Bread Base - Goodhearth'),
	 ('Bread Base - Italian'),
	 ('Bread Base - Toscano'),
	 ('Bread Bowl Plain'),
	 ('Bread Country Roll'),
	 ('Bread Crumbs - Japanese Style'),
	 ('Bread Crumbs - Panko'),
	 ('Bread Fig And Almond');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Bread Roll Foccacia'),
	 ('Bread Sour Rolls'),
	 ('Breadfruit'),
	 ('Breakfast Quesadillas'),
	 ('Broccoli - Fresh'),
	 ('Brocolinni - Gaylan,Chinese'),
	 ('Broom - Angled'),
	 ('Broom - Corn'),
	 ('Broom - Push'),
	 ('Broom And Broom Rack White');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Broom And Brush Rack Black'),
	 ('Broom Handle'),
	 ('Brownies - Two Bite,Chocolate'),
	 ('Browning Caramel Glace'),
	 ('Buffalo - Short Rib Fresh'),
	 ('Buffalo - Striploin'),
	 ('Buffalo - Tenderloin'),
	 ('Bulgar'),
	 ('Burger Veggie'),
	 ('Butcher Twine 4r');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Butter - Pod'),
	 ('Butter - Salted,Micro'),
	 ('Butter Balls Salted'),
	 ('Butter Ripple - Phillips'),
	 ('Butter Sweet'),
	 ('Buttons'),
	 ('C - Plus,Orange'),
	 ('Cabbage - Green'),
	 ('Cabbage - Nappa'),
	 ('Cabbage - Red');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cabbage - Savoy'),
	 ('Cabbage Roll'),
	 ('Cactus Pads'),
	 ('Cafe Royale'),
	 ('Cake - Box Window 10x10x2.5'),
	 ('Cake - Cake Sheet Macaroon'),
	 ('Cake - Cheese Cake 9 Inch'),
	 ('Cake - Dulce De Leche'),
	 ('Cake - French Pear Tart'),
	 ('Cake - Lemon Chiffon');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cake - Mini Cheesecake'),
	 ('Cake - Mini Potato Pancake'),
	 ('Cake - Night And Day Choclate'),
	 ('Cake - Sheet Strawberry'),
	 ('Cake Circle,Foil,Scallop'),
	 ('Cake Circle,Paprus'),
	 ('Cake Sheet Combo Party Pack'),
	 ('Cake Slab'),
	 ('Cakes Assorted'),
	 ('Calaloo');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Calvados - Boulard'),
	 ('Calypso - Black Cherry Lemonade'),
	 ('Calypso - Lemonade'),
	 ('Calypso - Pineapple Passion'),
	 ('Calypso - Strawberry Lemonade'),
	 ('Campari'),
	 ('Canada Dry'),
	 ('Canadian Emmenthal'),
	 ('Capers - Ox Eye Daisy'),
	 ('Capers - Pickled');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Capon - Breast,Double,Wing On'),
	 ('Capon - Breast,Wing On'),
	 ('Capon - Whole'),
	 ('Carbonated Water - Blackberry'),
	 ('Carbonated Water - Blackcherry'),
	 ('Carbonated Water - Cherry'),
	 ('Carbonated Water - Orange'),
	 ('Carbonated Water - Peach'),
	 ('Carbonated Water - Raspberry'),
	 ('Carbonated Water - Strawberry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Carbonated Water - White Grape'),
	 ('Carbonated Water - Wildberry'),
	 ('Carrots - Jumbo'),
	 ('Carrots - Mini Red Organic'),
	 ('Carrots - Mini,Stem On'),
	 ('Carrots - Purple,Organic'),
	 ('Cassis'),
	 ('Catfish - Fillets'),
	 ('Cattail Hearts'),
	 ('Cauliflower');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Caviar - Salmon'),
	 ('Celery'),
	 ('Celery Root'),
	 ('Chambord Royal'),
	 ('Champagne - Brights,Dry'),
	 ('Cheese - Asiago'),
	 ('Cheese - Bakers Cream Cheese'),
	 ('Cheese - Blue'),
	 ('Cheese - Boursin,Garlic / Herbs'),
	 ('Cheese - Brick With Onion');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Brick With Pepper'),
	 ('Cheese - Brie'),
	 ('Cheese - Brie Roitelet'),
	 ('Cheese - Brie,danish'),
	 ('Cheese - Cambozola'),
	 ('Cheese - Camembert'),
	 ('Cheese - Cheddar With Claret'),
	 ('Cheese - Cheddar,Medium'),
	 ('Cheese - Cheddar,Mild'),
	 ('Cheese - Cheddarsliced');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Colby'),
	 ('Cheese - Comte'),
	 ('Cheese - Comtomme'),
	 ('Cheese - Cottage Cheese'),
	 ('Cheese - Cream Cheese'),
	 ('Cheese - Ermite Bleu'),
	 ('Cheese - Feta'),
	 ('Cheese - Fontina'),
	 ('Cheese - Goat'),
	 ('Cheese - Gorgonzola');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Gouda'),
	 ('Cheese - Gouda Smoked'),
	 ('Cheese - Grie Des Champ'),
	 ('Cheese - Havarti,Salsa'),
	 ('Cheese - La Sauvagine'),
	 ('Cheese - Le Cheve Noir'),
	 ('Cheese - Le Cru Du Clocher'),
	 ('Cheese - Manchego,Spanish'),
	 ('Cheese - Mascarpone'),
	 ('Cheese - Mix');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Mozzarella,Buffalo'),
	 ('Cheese - Mozzarella,Shredded'),
	 ('Cheese - Oka'),
	 ('Cheese - Parmesan Cubes'),
	 ('Cheese - Parmesan Grated'),
	 ('Cheese - Parmigiano Reggiano'),
	 ('Cheese - Perron Cheddar'),
	 ('Cheese - Pied De Vents'),
	 ('Cheese - Pont Couvert'),
	 ('Cheese - Provolone');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Ricotta'),
	 ('Cheese - Romano,Grated'),
	 ('Cheese - Roquefort Pappillon'),
	 ('Cheese - Sheep Milk'),
	 ('Cheese - Shred Cheddar / Mozza'),
	 ('Cheese - St. Paulin'),
	 ('Cheese - Stilton'),
	 ('Cheese - Swiss'),
	 ('Cheese - Swiss Sliced'),
	 ('Cheese - Taleggio D.o.p.');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cheese - Valancey'),
	 ('Cheese - Victor Et Berthold'),
	 ('Cheese - Wine'),
	 ('Cheese - Woolwich Goat,Log'),
	 ('Cheese Cheddar Processed'),
	 ('Cheese Cloth'),
	 ('Cheese Cloth No 100'),
	 ('Cheese Cloth No 60'),
	 ('Chef Hat 20cm'),
	 ('Chef Hat 25cm');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cherries - Fresh'),
	 ('Cherries - Frozen'),
	 ('Cherries - Maraschino,jar'),
	 ('Chervil - Fresh'),
	 ('Chestnuts - Whole,canned'),
	 ('Chevere Logs'),
	 ('Chevril'),
	 ('Chick Peas - Canned'),
	 ('Chick Peas - Dried'),
	 ('Chicken - Base,Ultimate');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chicken - Bones'),
	 ('Chicken - Breast,5 - 7 Oz'),
	 ('Chicken - Diced,Cooked'),
	 ('Chicken - Ground'),
	 ('Chicken - Leg / Back Attach'),
	 ('Chicken - Leg,Boneless'),
	 ('Chicken - Leg,Fresh'),
	 ('Chicken - Livers'),
	 ('Chicken - Soup Base'),
	 ('Chicken - Tenderloin');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chicken - Thigh,Bone In'),
	 ('Chicken - White Meat With Tender'),
	 ('Chicken - White Meat,No Tender'),
	 ('Chicken - Whole'),
	 ('Chicken - Whole Fryers'),
	 ('Chicken - Whole Roasting'),
	 ('Chicken - Wieners'),
	 ('Chicken Breast Halal'),
	 ('Chicken Breast Wing On'),
	 ('Chicken Giblets');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chicken Thigh - Bone Out'),
	 ('Chickhen - Chicken Phyllo'),
	 ('Chilli Paste,Ginger Garlic'),
	 ('Chilli Paste,Hot Sambal Oelek'),
	 ('Chilli Paste,Sambal Oelek'),
	 ('Chinese Foods - Cantonese'),
	 ('Chinese Foods - Chicken'),
	 ('Chinese Foods - Chicken Wing'),
	 ('Chinese Foods - Pepper Beef'),
	 ('Chinese Foods - Plain Fried Rice');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chinese Foods - Thick Noodles'),
	 ('Chinese Lemon Pork'),
	 ('Chip - Potato Dill Pickle'),
	 ('Chips - Assorted'),
	 ('Chips - Doritos'),
	 ('Chips Potato All Dressed - 43g'),
	 ('Chips Potato Reg 43g'),
	 ('Chips Potato Salt Vinegar 43g'),
	 ('Chivas Regal - 12 Year Old'),
	 ('Chives - Fresh');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chocolate - Chips Compound'),
	 ('Chocolate - Compound Coating'),
	 ('Chocolate - Dark'),
	 ('Chocolate - Dark Callets'),
	 ('Chocolate - Feathers'),
	 ('Chocolate - Liqueur Cups With Foil'),
	 ('Chocolate - Mi - Amere Semi'),
	 ('Chocolate - Milk Coating'),
	 ('Chocolate - Pistoles,Lactee,Milk'),
	 ('Chocolate - Pistoles,White');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Chocolate - Sugar Free Semi Choc'),
	 ('Chocolate - Unsweetened'),
	 ('Chocolate - White'),
	 ('Chocolate Bar - Coffee Crisp'),
	 ('Chocolate Bar - Oh Henry'),
	 ('Chocolate Bar - Reese Pieces'),
	 ('Chocolate Bar - Smarties'),
	 ('Chocolate Eclairs'),
	 ('Chocolate Liqueur - Godet White'),
	 ('Chutney Sauce - Mango');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cinnamon - Ground'),
	 ('Cinnamon - Stick'),
	 ('Cinnamon Buns Sticky'),
	 ('Cinnamon Rolls'),
	 ('Clam Nectar'),
	 ('Clams - Bay'),
	 ('Clams - Canned'),
	 ('Clams - Littleneck,Whole'),
	 ('Cleaner - Bleach'),
	 ('Cleaner - Comet');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cleaner - Lime Away'),
	 ('Clementine'),
	 ('Cloves - Ground'),
	 ('Cloves - Whole'),
	 ('Club Soda - Schweppes,355 Ml'),
	 ('Cocktail Napkin Blue'),
	 ('Cocoa Butter'),
	 ('Cocoa Feuilletine'),
	 ('Cocoa Powder - Dutched'),
	 ('Cocoa Powder - Natural');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Coconut - Creamed,Pure'),
	 ('Coconut - Shredded,Sweet'),
	 ('Coconut - Whole'),
	 ('Coconut Milk - Unsweetened'),
	 ('Cod - Black Whole Fillet'),
	 ('Cod - Fillets'),
	 ('Cod - Salted,Boneless'),
	 ('Coffee - 10oz Cup 92961'),
	 ('Coffee - Almond Amaretto'),
	 ('Coffee - Beans,Whole');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Coffee - Cafe Moreno'),
	 ('Coffee - Colombian,Portioned'),
	 ('Coffee - Dark Roast'),
	 ('Coffee - Decaffeinato Coffee'),
	 ('Coffee - Egg Nog Capuccino'),
	 ('Coffee - Espresso'),
	 ('Coffee - Flavoured'),
	 ('Coffee - French Vanilla Frothy'),
	 ('Coffee - Frthy Coffee Crisp'),
	 ('Coffee - Hazelnut Cream');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Coffee - Irish Cream'),
	 ('Coffee - Ristretto Coffee Capsule'),
	 ('Coffee Beans - Chocolate'),
	 ('Coffee Caramel Biscotti'),
	 ('Coffee Cup 12oz 5342cd'),
	 ('Coffee Cup 16oz Foam'),
	 ('Coffee Decaf Colombian'),
	 ('Coffee Guatemala Dark'),
	 ('Coffee Swiss Choc Almond'),
	 ('Cognac - Courvaisier');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Coke - Classic,355 Ml'),
	 ('Coke - Diet,355 Ml'),
	 ('Compound - Mocha'),
	 ('Compound - Orange'),
	 ('Compound - Passion Fruit'),
	 ('Compound - Pear'),
	 ('Compound - Rum'),
	 ('Compound - Strawberry'),
	 ('Container - Clear 16 Oz'),
	 ('Container - Clear 32 Oz');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Container - Foam Dixie 12 Oz'),
	 ('Container - Hngd Cll Blk 7x7x3'),
	 ('Container Clear 8 Oz'),
	 ('Containter - 3oz Microwave Rect.'),
	 ('Contreau'),
	 ('Cookie Choc'),
	 ('Cookie Chocolate Chip With'),
	 ('Cookie Double Choco'),
	 ('Cookie Dough - Chocolate Chip'),
	 ('Cookie Dough - Chunky');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cookie Dough - Double'),
	 ('Cookie Dough - Oatmeal Rasin'),
	 ('Cookie Dough - Peanut Butter'),
	 ('Cookie Trail Mix'),
	 ('Cookies - Amaretto'),
	 ('Cookies - Assorted'),
	 ('Cookies - Englishbay Chochip'),
	 ('Cookies - Englishbay Oatmeal'),
	 ('Cookies - Englishbay Wht'),
	 ('Cookies - Fortune');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cookies - Oreo,4 Pack'),
	 ('Cookies Almond Hazelnut'),
	 ('Cookies Cereal Nut'),
	 ('Coriander - Ground'),
	 ('Coriander - Seed'),
	 ('Corn - Cream,Canned'),
	 ('Corn - Mini'),
	 ('Corn - On The Cob'),
	 ('Corn Kernels - Frozen'),
	 ('Corn Meal');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Corn Shoots'),
	 ('Cornish Hen'),
	 ('Cornstarch'),
	 ('Cotton Wet Mop 16 Oz'),
	 ('Country Roll'),
	 ('Couscous'),
	 ('Crab - Back Fin Meat,Canned'),
	 ('Crab - Blue,Frozen'),
	 ('Crab - Claws,26 - 30'),
	 ('Crab - Claws,Snow 16 - 24');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Crab - Dungeness,Whole'),
	 ('Crab - Dungeness,Whole,live'),
	 ('Crab - Imitation Flakes'),
	 ('Crab - Meat'),
	 ('Crab - Meat Combo'),
	 ('Crab - Soft Shell'),
	 ('Crab Brie In Phyllo'),
	 ('Crab Meat Claw Pasteurise'),
	 ('Crackers - Graham'),
	 ('Crackers - Melba Toast');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Crackers - Soda / Saltins'),
	 ('Crackers - Trio'),
	 ('Crackers Cheez It'),
	 ('Cranberries - Dry'),
	 ('Cranberries - Fresh'),
	 ('Cranberries - Frozen'),
	 ('Cranberry Foccacia'),
	 ('Crawfish'),
	 ('Cream - 10%'),
	 ('Cream Of Tartar');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Creamers - 10%'),
	 ('Creme De Banane - Marie'),
	 ('Creme De Cacao Mcguines'),
	 ('Creme De Cacao White'),
	 ('Creme De Menth - White'),
	 ('Creme De Menthe Green'),
	 ('Croissant,Raw - Mini'),
	 ('Croissants Thaw And Serve'),
	 ('Crush - Cream Soda'),
	 ('Crush - Grape,355 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Crush - Orange,355ml'),
	 ('Cucumber - English'),
	 ('Cucumber - Pickling Ontario'),
	 ('Cumin - Ground'),
	 ('Cup - 3.5oz,Foam'),
	 ('Cup - 4oz Translucent'),
	 ('Cup - 6oz,Foam'),
	 ('Cup - 8oz Coffee Perforated'),
	 ('Cup - Paper 10oz 92959'),
	 ('Cup - Translucent 7 Oz Clear');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Cup Translucent 9 Oz'),
	 ('Cups 10oz Trans'),
	 ('Currants'),
	 ('Curry Paste - Green Masala'),
	 ('Curry Powder'),
	 ('Curry Powder Madras'),
	 ('Cut Wakame - Hanawakaba'),
	 ('Daikon Radish'),
	 ('Danishes - Mini Cheese'),
	 ('Dasheen');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Dates'),
	 ('Daves Island Stinger'),
	 ('Dawn Professionl Pot And Pan'),
	 ('Dc - Frozen Momji'),
	 ('Dc - Sakura Fu'),
	 ('Dc Hikiage Hira Huba'),
	 ('Dehydrated Kelp Kombo'),
	 ('Devonshire Cream'),
	 ('Dill - Primerba,Paste'),
	 ('Dill Weed - Dry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Dill Weed - Fresh'),
	 ('Dip - Tapenade'),
	 ('Dish Towel'),
	 ('Doilies - 10,Paper'),
	 ('Doilies - 12,Paper'),
	 ('Doilies - 5,Paper'),
	 ('Doilies - 7,Paper'),
	 ('Doilies - 8,Paper'),
	 ('Dome Lid Clear P92008h'),
	 ('Dooleys Toffee');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Dr. Pepper - 355ml'),
	 ('Drambuie'),
	 ('Dried Apple'),
	 ('Dried Cranberries'),
	 ('Dried Figs'),
	 ('Dried Peach'),
	 ('Duck - Breast'),
	 ('Duck - Fat'),
	 ('Duck - Legs'),
	 ('Duck - Whole');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Durian Fruit'),
	 ('Easy Off Oven Cleaner'),
	 ('Ecolab - Balanced Fusion'),
	 ('Ecolab - Hobart Upr Prewash Arm'),
	 ('Ecolab - Hobart Washarm End Cap'),
	 ('Ecolab - Lime - A - Way 4/4 L'),
	 ('Ecolab - Medallion'),
	 ('Ecolab - Mikroklene 4/4 L'),
	 ('Ecolab - Orange Frc,Cleaner'),
	 ('Ecolab - Power Fusion');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Ecolab - Solid Fusion'),
	 ('Ecolab - Ster Bac'),
	 ('Ecolab Crystal Fusion'),
	 ('Ecolab Digiclean Mild Fm'),
	 ('Edible Flower - Mixed'),
	 ('Eel - Smoked'),
	 ('Eel Fresh'),
	 ('Egg - Salad Premix'),
	 ('Egg Patty Fried'),
	 ('Eggplant - Baby');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Eggplant Italian'),
	 ('Eggplant Oriental'),
	 ('Eggroll'),
	 ('Eggs - Extra Large'),
	 ('Eggwhite Frozen'),
	 ('Emulsifier'),
	 ('Energy - Boo - Koo'),
	 ('Energy Drink'),
	 ('Energy Drink - Franks Original'),
	 ('Energy Drink - Franks Pineapple');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Energy Drink - Redbull 355ml'),
	 ('English Muffin'),
	 ('Evaporated Milk - Skim'),
	 ('Everfresh Products'),
	 ('External Supplier'),
	 ('Extract - Almond'),
	 ('Extract - Lemon'),
	 ('Extract - Raspberry'),
	 ('Extract - Rum'),
	 ('Extract - Vanilla,artificial');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Extract Vanilla Pure'),
	 ('Ezy Change Mophandle'),
	 ('Fennel'),
	 ('Fennel - Seeds'),
	 ('Fenngreek Seed'),
	 ('Figs'),
	 ('Filo Dough'),
	 ('Filter - Coffee'),
	 ('Fireball Whisky'),
	 ('Fish - Atlantic Salmon,Cold');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Fish - Base,Bouillion'),
	 ('Fish - Scallops,Cold Smoked'),
	 ('Fish - Soup Base,Bouillon'),
	 ('Five Alive Citrus'),
	 ('Flavouring - Orange'),
	 ('Flavouring - Raspberry'),
	 ('Flavouring - Rum'),
	 ('Flavouring Vanilla Artificial'),
	 ('Flax Seed'),
	 ('Flounder - Fresh');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Flour - All Purpose'),
	 ('Flour - Bran,Red'),
	 ('Flour - Bread'),
	 ('Flour - Buckwheat,Dark'),
	 ('Flour - Cake'),
	 ('Flour - Corn,Fine'),
	 ('Flour - Fast / Rapid'),
	 ('Flour - Masa De Harina Mexican'),
	 ('Flour - Rye'),
	 ('Flour - Semolina');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Flour - So Mix Cake White'),
	 ('Flour - Teff'),
	 ('Flour - Whole Wheat'),
	 ('Flour Dark Rye'),
	 ('Flour Pastry Super Fine'),
	 ('Flower - Carnations'),
	 ('Flower - Commercial Bronze'),
	 ('Flower - Commercial Spider'),
	 ('Flower - Daisies'),
	 ('Flower - Dish Garden');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Flower - Leather Leaf Fern'),
	 ('Flower - Potmums'),
	 ('Foam Cup 6 Oz'),
	 ('Foam Dinner Plate'),
	 ('Foam Espresso Cup Plain White'),
	 ('Foam Tray S2'),
	 ('Foil - 4oz Custard Cup'),
	 ('Foil - Round Foil'),
	 ('Foil Cont Round'),
	 ('Foil Wrap');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Fond - Chocolate'),
	 ('Fond - Neutral'),
	 ('Food Colouring - Green'),
	 ('Food Colouring - Orange'),
	 ('Food Colouring - Pink'),
	 ('Food Colouring - Red'),
	 ('Fork - Plastic'),
	 ('Frangelico'),
	 ('French Kiss Vanilla'),
	 ('French Pastries');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('French Pastry - Mini Chocolate'),
	 ('Fruit Salad Deluxe'),
	 ('Fudge - Chocolate Fudge'),
	 ('Fudge - Cream Fudge'),
	 ('Fuji Apples'),
	 ('Galliano'),
	 ('Garbag Bags - Black'),
	 ('Garbage Bag - Clear'),
	 ('Garbage Bags - Black'),
	 ('Garbage Bags - Clear');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Garlic'),
	 ('Garlic - Peeled'),
	 ('Garlic - Primerba,Paste'),
	 ('Garlic Powder'),
	 ('Gatorade - Cool Blue Raspberry'),
	 ('Gatorade - Lemon Lime'),
	 ('Gatorade - Orange'),
	 ('Gatorade - Xfactor Berry'),
	 ('Gelatine Leaves - Bulk'),
	 ('Gelatine Leaves - Envelopes');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Gelatine Powder'),
	 ('Gherkin'),
	 ('Gherkin - Sour'),
	 ('Gin - Gilbeys London,Dry'),
	 ('Ginger - Crystalized'),
	 ('Ginger - Fresh'),
	 ('Ginger - Ground'),
	 ('Ginger - Pickled'),
	 ('Gingerale - Diet - Schweppes'),
	 ('Gingerale - Schweppes,355 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Ginsing - Fresh'),
	 ('Glass - Juice Clear 5oz 55005'),
	 ('Glass - Wine,Plastic,Clear 5 Oz'),
	 ('Glass Clear 7 Oz Xl'),
	 ('Glass Clear 8 Oz'),
	 ('Glaze - Apricot'),
	 ('Glaze - Clear'),
	 ('Glove - Cutting'),
	 ('Gloves - Goldtouch Disposable'),
	 ('Glucose');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Glycerine'),
	 ('Goat - Leg'),
	 ('Goldschalger'),
	 ('Gooseberry'),
	 ('Goulash Seasoning'),
	 ('Graham Cracker Mix'),
	 ('Grapefruit - White'),
	 ('Grapes - Black'),
	 ('Grapes - Red'),
	 ('Green Scrubbie Pad H.duty');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Green Tea Refresher'),
	 ('Greens Mustard'),
	 ('Grenadillo'),
	 ('Grouper - Fresh'),
	 ('Guava'),
	 ('Guinea Fowl'),
	 ('Hagen Daza - Dk Choocolate'),
	 ('Haggis'),
	 ('Halibut - Fletches'),
	 ('Halibut - Steaks');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Halibut - Whole,Fresh'),
	 ('Ham - Cooked'),
	 ('Ham - Cooked Italian'),
	 ('Ham - Procutinni'),
	 ('Ham - Smoked,Bone - In'),
	 ('Heavy Duty Dust Pan'),
	 ('Herb Du Provence - Primerba'),
	 ('Hersey Shakes'),
	 ('Hickory Smoke,Liquid'),
	 ('Higashimaru Usukuchi Soy');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Hinge W Undercut'),
	 ('Hipnotiq Liquor'),
	 ('Hog / Sausage Casing - Pork'),
	 ('Hold Up Tool Storage Rack'),
	 ('Honey - Comb'),
	 ('Honey - Lavender'),
	 ('Honey - Liquid'),
	 ('Horseradish - Prepared'),
	 ('Horseradish Root'),
	 ('Hot Choc Vending');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Hot Chocolate - Individual'),
	 ('Huck Towels White'),
	 ('Huck White Towels'),
	 ('Ice - Clear,300 Lb For Carving'),
	 ('Ice Cream - Chocolate'),
	 ('Ice Cream - Life Savers'),
	 ('Ice Cream - Strawberry'),
	 ('Ice Cream - Turtles Stick Bar'),
	 ('Ice Cream - Vanilla'),
	 ('Ice Cream Bar - Drumstick');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Ice Cream Bar - Hageen Daz To'),
	 ('Ice Cream Bar - Hagen Daz'),
	 ('Ice Cream Bar - Oreo Cone'),
	 ('Ice Cream Bar - Oreo Sandwich'),
	 ('Ice Cream Bar - Rolo Cone'),
	 ('Icecream - Dstk Cml And Fdg'),
	 ('Icecream - Dstk Strw Chseck'),
	 ('Icecream - Dstk Super Cone'),
	 ('Icecream Bar - Del Monte'),
	 ('Icecream Cone - Areo Chocolate');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Iced Tea - Lemon,340ml'),
	 ('Iced Tea - Lemon,460 Ml'),
	 ('Iced Tea Concentrate'),
	 ('Initation Crab Meat'),
	 ('Instant Coffee'),
	 ('Irish Cream - Baileys'),
	 ('Irish Cream - Butterscotch'),
	 ('Island Oasis - Banana Daiquiri'),
	 ('Island Oasis - Cappucino Mix'),
	 ('Island Oasis - Ice Cream Mix');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Island Oasis - Magarita Mix'),
	 ('Island Oasis - Mango Daiquiri'),
	 ('Island Oasis - Peach Daiquiri'),
	 ('Island Oasis - Pina Colada'),
	 ('Island Oasis - Raspberry'),
	 ('Island Oasis - Strawberry'),
	 ('Island Oasis - Sweet And Sour Mix'),
	 ('Isomalt'),
	 ('Jack Daniels'),
	 ('Jagermeister');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Jam - Apricot'),
	 ('Jam - Marmalade,Orange'),
	 ('Jam - Raspberry,jar'),
	 ('Jam - Strawberry,20 Ml Jar'),
	 ('Jameson - Irish Whiskey'),
	 ('Jameson Irish Whiskey'),
	 ('Jello - Assorted'),
	 ('Jerusalem Artichoke'),
	 ('Jicama'),
	 ('Jolt Cola');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Jolt Cola - Electric Blue'),
	 ('Juice - Apple 284ml'),
	 ('Juice - Apple Cider'),
	 ('Juice - Apple,341 Ml'),
	 ('Juice - Apple,500 Ml'),
	 ('Juice - Clam,46 Oz'),
	 ('Juice - Clamato,341 Ml'),
	 ('Juice - Cranberry 284ml'),
	 ('Juice - Grape,White'),
	 ('Juice - Grapefruit,341 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Juice - Happy Planet'),
	 ('Juice - Lagoon Mango'),
	 ('Juice - Lemon'),
	 ('Juice - Lime'),
	 ('Juice - Mango'),
	 ('Juice - Ocean Spray Cranberry'),
	 ('Juice - Ocean Spray Kiwi'),
	 ('Juice - Orange'),
	 ('Juice - Orange 1.89l'),
	 ('Juice - Orange,341 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Juice - Orange,Concentrate'),
	 ('Juice - Orangina'),
	 ('Juice - Pineapple,48 Oz'),
	 ('Juice - Propel Sport'),
	 ('Juice - Tomato,10 Oz'),
	 ('Juice - Tomato,48 Oz'),
	 ('Juice - V8 Splash'),
	 ('Juice - V8,Tomato'),
	 ('Juice Peach Nectar'),
	 ('Kaffir Lime Leaves');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Kahlua'),
	 ('Kale - Red'),
	 ('Kellogs All Bran Bars'),
	 ('Kellogs Cereal In A Cup'),
	 ('Kellogs Special K Cereal'),
	 ('Ketchup - Tomato'),
	 ('Kippers - Smoked'),
	 ('Kirsch - Schloss'),
	 ('Kiwano'),
	 ('Kiwi');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Kiwi Gold Zespri'),
	 ('Knife Plastic - White'),
	 ('Kohlrabi'),
	 ('Kolrabi'),
	 ('Kumquat'),
	 ('Lady Fingers'),
	 ('Lamb - Bones'),
	 ('Lamb - Ground'),
	 ('Lamb - Leg,Bone In'),
	 ('Lamb - Leg,Boneless');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lamb - Leg,Diced'),
	 ('Lamb - Loin Chops'),
	 ('Lamb - Loin,Trimmed,Boneless'),
	 ('Lamb - Pieces,Diced'),
	 ('Lamb - Rack'),
	 ('Lamb - Racks,Frenched'),
	 ('Lamb - Sausage Casings'),
	 ('Lamb - Shanks'),
	 ('Lamb - Shoulder,Boneless'),
	 ('Lamb - Whole Head Off');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lamb - Whole Head Off,nz'),
	 ('Lamb - Whole,Fresh'),
	 ('Lamb - Whole,Frozen'),
	 ('Lamb Leg - Bone - In Nz'),
	 ('Lamb Rack - Ontario'),
	 ('Lamb Shoulder Boneless Nz'),
	 ('Lamb Tenderloin Nz Fr'),
	 ('Lambcasing'),
	 ('Langers - Cranberry Cocktail'),
	 ('Langers - Mango Nectar');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Langers - Ruby Red Grapfruit'),
	 ('Latex Rubber Gloves Size 9'),
	 ('Laundry - Bag Cloth'),
	 ('Leeks - Baby,White'),
	 ('Leeks - Large'),
	 ('Lemon Balm - Fresh'),
	 ('Lemon Grass'),
	 ('Lemon Pepper'),
	 ('Lemon Tarts'),
	 ('Lemonade - Black Cherry,591 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lemonade - Island Tea,591 Ml'),
	 ('Lemonade - Mandarin,591 Ml'),
	 ('Lemonade - Natural,591 Ml'),
	 ('Lemonade - Pineapple Passion'),
	 ('Lemonade - Strawberry,591 Ml'),
	 ('Lemons'),
	 ('Lentils - Green Le Puy'),
	 ('Lettuce - Arugula'),
	 ('Lettuce - Baby Salad Greens'),
	 ('Lettuce - Belgian Endive');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lettuce - Boston Bib'),
	 ('Lettuce - Boston Bib - Organic'),
	 ('Lettuce - California Mix'),
	 ('Lettuce - Curly Endive'),
	 ('Lettuce - Escarole'),
	 ('Lettuce - Frisee'),
	 ('Lettuce - Green Leaf'),
	 ('Lettuce - Iceberg'),
	 ('Lettuce - Lolla Rosa'),
	 ('Lettuce - Radicchio');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lettuce - Red Leaf'),
	 ('Lettuce - Romaine,Heart'),
	 ('Lettuce - Sea / Sea Asparagus'),
	 ('Lettuce - Spring Mix'),
	 ('Lettuce Romaine Chopped'),
	 ('Lid - 0090 Clear'),
	 ('Lid - 10,12,16 Oz'),
	 ('Lid - 16 Oz And 32 Oz'),
	 ('Lid - 3oz Med Rec'),
	 ('Lid - High Heat,Super Clear');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lid - Translucent,3.5 And 6 Oz'),
	 ('Lid Coffee Cup 8oz Blk'),
	 ('Lid Coffeecup 12oz D9542b'),
	 ('Lid Tray - 12in Dome'),
	 ('Lid Tray - 16in Dome'),
	 ('Lidsoupcont Rp12dn'),
	 ('Lighter - Bbq'),
	 ('Lime Cordial - Roses'),
	 ('Limes'),
	 ('Liners - Baking Cups');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Liners - Banana,Paper'),
	 ('Liqueur - Melon'),
	 ('Liqueur Banana,Ramazzotti'),
	 ('Liquid Aminios Acid - Braggs'),
	 ('Loaf Pan - 2 Lb,Foil'),
	 ('Lobak'),
	 ('Lobster - Baby,Boiled'),
	 ('Lobster - Base'),
	 ('Lobster - Canned Premium'),
	 ('Lobster - Cooked');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lobster - Live'),
	 ('Lobster - Tail 6 Oz'),
	 ('Longos - Assorted Sandwich'),
	 ('Longos - Burritos'),
	 ('Longos - Chicken Caeser Salad'),
	 ('Longos - Chicken Cordon Bleu'),
	 ('Longos - Chicken Curried'),
	 ('Longos - Chicken Wings'),
	 ('Longos - Greek Salad'),
	 ('Longos - Grilled Chicken With');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Longos - Grilled Salmon With Bbq'),
	 ('Longos - Grilled Veg Sandwiches'),
	 ('Longos - Lasagna Beef'),
	 ('Longos - Lasagna Veg'),
	 ('Longos - Penne With Pesto'),
	 ('Loquat'),
	 ('Lotus Leaves'),
	 ('Lotus Root'),
	 ('Lotus Rootlets - Canned'),
	 ('Lumpfish Black');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Lychee'),
	 ('Lychee - Canned'),
	 ('Macaroons - Homestyle Two Bit'),
	 ('Macaroons - Two Bite Choc'),
	 ('Mace'),
	 ('Mace Ground'),
	 ('Mackerel Whole Fresh'),
	 ('Madeira'),
	 ('Magnotta - Bel Paese White'),
	 ('Mahi Mahi');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Mangoes'),
	 ('Mangostein'),
	 ('Maple Syrup'),
	 ('Marjoram - Dried,Rubbed'),
	 ('Marjoram - Fresh'),
	 ('Marsala - Sperone,Fine,D.o.c.'),
	 ('Marzipan 50/50'),
	 ('Mayonnaise'),
	 ('Mcguinness - Blue Curacao'),
	 ('Meldea Green Tea Liquor');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Melon - Cantaloupe'),
	 ('Melon - Honey Dew'),
	 ('Melon - Watermelon Yellow'),
	 ('Melon - Watermelon,Seedless'),
	 ('Mikes Hard Lemonade'),
	 ('Milk - 1%'),
	 ('Milk - 2%'),
	 ('Milk - 2% 250 Ml'),
	 ('Milk - Buttermilk'),
	 ('Milk - Chocolate 250 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Milk - Chocolate 500ml'),
	 ('Milk - Homo'),
	 ('Milk - Skim'),
	 ('Milk 2% 500 Ml'),
	 ('Milk Powder'),
	 ('Milkettes - 2%'),
	 ('Mince Meat - Filling'),
	 ('Mint - Fresh'),
	 ('Miso - Soy Bean Paste'),
	 ('Miso Paste White');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Mix - Cappucino Cocktail'),
	 ('Mix - Cocktail Ice Cream'),
	 ('Mix - Cocktail Strawberry Daiquiri'),
	 ('Mix Pina Colada'),
	 ('Molasses - Fancy'),
	 ('Momiji Oroshi Chili Sauce'),
	 ('Monkfish - Fresh'),
	 ('Monkfish Fresh - Skin Off'),
	 ('Mop Head - Cotton,24 Oz'),
	 ('Mountain Dew');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Mousse - Banana Chocolate'),
	 ('Mousse - Mango'),
	 ('Mousse - Passion Fruit'),
	 ('Mudslide'),
	 ('Muffin - Banana Nut Individual'),
	 ('Muffin - Blueberry Individual'),
	 ('Muffin - Bran Ind Wrpd'),
	 ('Muffin - Carrot Individual Wrap'),
	 ('Muffin - Mix - Bran And Maple 15l'),
	 ('Muffin - Mix - Creme Brule 15l');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Muffin - Mix - Mango Sour Cherry'),
	 ('Muffin - Mix - Strawberry Rhubarb'),
	 ('Muffin - Zero Transfat'),
	 ('Muffin Batt - Ban Dream Zero'),
	 ('Muffin Batt - Blueberry Passion'),
	 ('Muffin Batt - Carrot Spice'),
	 ('Muffin Batt - Choc Chk'),
	 ('Muffin Carrot - Individual'),
	 ('Muffin Chocolate Individual Wrap'),
	 ('Muffin Hinge - 211n');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Muffin Hinge Container 6'),
	 ('Muffin Mix - Blueberry'),
	 ('Muffin Mix - Carrot'),
	 ('Muffin Mix - Chocolate Chip'),
	 ('Muffin Mix - Lemon Cranberry'),
	 ('Muffin Mix - Morning Glory'),
	 ('Muffin Mix - Oatmeal'),
	 ('Muffin Mix - Raisin Bran'),
	 ('Muffin Orange Individual'),
	 ('Muffin Puck Ww Carrot');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Muffins - Assorted'),
	 ('Munchies Honey Sweet Trail Mix'),
	 ('Mushroom - Chanterelle Frozen'),
	 ('Mushroom - Chanterelle,Dry'),
	 ('Mushroom - Chantrelle,Fresh'),
	 ('Mushroom - Crimini'),
	 ('Mushroom - Enoki,Dry'),
	 ('Mushroom - Enoki,Fresh'),
	 ('Mushroom - King Eryingii'),
	 ('Mushroom - Lg - Cello');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Mushroom - Morel Frozen'),
	 ('Mushroom - Oyster,Fresh'),
	 ('Mushroom - Porcini Frozen'),
	 ('Mushroom - Porcini,Dry'),
	 ('Mushroom - Portebello'),
	 ('Mushroom - Shitake,Dry'),
	 ('Mushroom - Shitake,Fresh'),
	 ('Mushroom - Trumpet,Dry'),
	 ('Mushroom - White Button'),
	 ('Mushroom Morel Fresh');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Mushrooms - Black,Dried'),
	 ('Mushrooms - Honey'),
	 ('Muskox - French Rack'),
	 ('Mussels - Frozen'),
	 ('Mustard - Dijon'),
	 ('Mustard - Dry,Powder'),
	 ('Mustard - Individual Pkg'),
	 ('Mustard - Pommery'),
	 ('Mustard - Seed'),
	 ('Mustard Prepared');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Nacho Chips'),
	 ('Nantucket - 518ml'),
	 ('Nantucket - Carrot Orange'),
	 ('Nantucket - Kiwi Berry Cktl.'),
	 ('Nantucket - Pomegranate Pear'),
	 ('Nantucket Apple Juice'),
	 ('Nantucket Cranberry Juice'),
	 ('Nantucket Orange Juice'),
	 ('Nantuket Peach Orange'),
	 ('Napkin - Beverage 1 Ply');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Napkin - Beverge,White 2 - Ply'),
	 ('Napkin - Cocktail,beige 2 - Ply'),
	 ('Napkin - Dinner,White'),
	 ('Napkin Colour'),
	 ('Napkin White'),
	 ('Napkin White - Starched'),
	 ('Neckerchief Blck'),
	 ('Nectarines'),
	 ('Nescafe - Frothy French Vanilla'),
	 ('Nestea - Ice Tea,Diet');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Nestea - Iced Tea'),
	 ('Noodles - Cellophane,Thin'),
	 ('Noodles - Steamed Chow Mein'),
	 ('Nori Sea Weed'),
	 ('Nori Sea Weed - Gold Label'),
	 ('Nougat - Paste / Cream'),
	 ('Numi - Assorted Teas'),
	 ('Nut - Almond,Blanched,Ground'),
	 ('Nut - Almond,Blanched,Sliced'),
	 ('Nut - Almond,Blanched,Whole');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Nut - Cashews,Whole,Raw'),
	 ('Nut - Chestnuts,Whole'),
	 ('Nut - Hazelnut,Ground,Natural'),
	 ('Nut - Hazelnut,Whole'),
	 ('Nut - Macadamia'),
	 ('Nut - Peanut,Roasted'),
	 ('Nut - Pecan,Halves'),
	 ('Nut - Pecan,Pieces'),
	 ('Nut - Pine Nuts,Whole'),
	 ('Nut - Pistachio,Shelled');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Nut - Pumpkin Seeds'),
	 ('Nut - Walnut,Chopped'),
	 ('Nut - Walnut,Pieces'),
	 ('Nutmeg - Ground'),
	 ('Oats Large Flake'),
	 ('Ocean Spray - Kiwi Strawberry'),
	 ('Ocean Spray - Ruby Red'),
	 ('Octopus'),
	 ('Octopus - Baby,Cleaned'),
	 ('Oil - Avocado');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Oil - Canola'),
	 ('Oil - Coconut'),
	 ('Oil - Cooking Spray'),
	 ('Oil - Food,Lacquer Spray'),
	 ('Oil - Grapeseed Oil'),
	 ('Oil - Hazelnut'),
	 ('Oil - Macadamia'),
	 ('Oil - Margarine'),
	 ('Oil - Olive Bertolli'),
	 ('Oil - Olive,Extra Virgin');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Oil - Peanut'),
	 ('Oil - Pumpkinseed'),
	 ('Oil - Safflower'),
	 ('Oil - Sesame'),
	 ('Oil - Shortening - All - Purpose'),
	 ('Oil - Shortening,liqud,Fry'),
	 ('Oil - Sunflower'),
	 ('Oil - Truffle,Black'),
	 ('Oil - Truffle,White'),
	 ('Okra');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Olive - Spread Tapenade'),
	 ('Olives - Black,Pitted'),
	 ('Olives - Green,Pitted'),
	 ('Olives - Kalamata'),
	 ('Olives - Morracan Dired'),
	 ('Olives - Nicoise'),
	 ('Olives - Stuffed'),
	 ('Oneshot Automatic Soap System'),
	 ('Onion - Dried'),
	 ('Onion Powder');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Onions - Cippolini'),
	 ('Onions - Cooking'),
	 ('Onions - Dried,Chopped'),
	 ('Onions - Green'),
	 ('Onions - Pearl'),
	 ('Onions - Red Pearl'),
	 ('Onions - Vidalia'),
	 ('Onions - White'),
	 ('Onions Granulated'),
	 ('Orange - Canned,Mandarin');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Orange - Tangerine'),
	 ('Orange Roughy 4/6 Oz'),
	 ('Orange Roughy 6/8 Oz'),
	 ('Oranges'),
	 ('Oranges - Navel,72'),
	 ('Oregano - Dry,Rubbed'),
	 ('Oregano - Fresh'),
	 ('Ostrich - Fan Fillet'),
	 ('Otomegusa Dashi Konbu'),
	 ('Oven Mitt - 13 Inch');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Oven Mitts - 15 Inch'),
	 ('Oven Mitts 17 Inch'),
	 ('Oxtail - Cut'),
	 ('Oyster - In Shell'),
	 ('Oysters - Smoked'),
	 ('Pail - 15l White,With Handle'),
	 ('Pail - 4l White,With Handle'),
	 ('Pail For Lid 1537'),
	 ('Pail With Metal Handle 16l White'),
	 ('Pails With Lids');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pan Grease'),
	 ('Pancetta'),
	 ('Pants Custom Dry Clean'),
	 ('Papadam'),
	 ('Papayas'),
	 ('Paper - Brown Paper Mini Cups'),
	 ('Paper Cocktail Umberlla 80 - 180'),
	 ('Paper Towel Touchless'),
	 ('Parsley - Dried'),
	 ('Parsley - Fresh');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Parsley Italian - Fresh'),
	 ('Parsnip'),
	 ('Passion Fruit'),
	 ('Pasta - Agnolotti - Butternut'),
	 ('Pasta - Angel Hair'),
	 ('Pasta - Bauletti,Chicken White'),
	 ('Pasta - Canelloni'),
	 ('Pasta - Canelloni,Single Serve'),
	 ('Pasta - Cannelloni,Sheets,Fresh'),
	 ('Pasta - Cappellini,Dry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pasta - Cheese / Spinach Bauletti'),
	 ('Pasta - Elbows,Macaroni,Dry'),
	 ('Pasta - Fett Alfredo,Single Serve'),
	 ('Pasta - Fettuccine,Dry'),
	 ('Pasta - Fettuccine,Egg,Fresh'),
	 ('Pasta - Fusili Tri - Coloured'),
	 ('Pasta - Fusili,Dry'),
	 ('Pasta - Gnocchi,Potato'),
	 ('Pasta - Lasagna Noodle,Frozen'),
	 ('Pasta - Lasagna,Dry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pasta - Lasagne,Fresh'),
	 ('Pasta - Linguini,Dry'),
	 ('Pasta - Orzo,Dry'),
	 ('Pasta - Penne Primavera,Single'),
	 ('Pasta - Penne,Lisce,Dry'),
	 ('Pasta - Penne,Rigate,Dry'),
	 ('Pasta - Ravioli'),
	 ('Pasta - Rotini,Colour,Dry'),
	 ('Pasta - Rotini,Dry'),
	 ('Pasta - Shells,Medium,Dry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pasta - Spaghetti,Dry'),
	 ('Pasta - Tortellini,Fresh'),
	 ('Pastrami'),
	 ('Pastry - Apple Large'),
	 ('Pastry - Apple Muffins - Mini'),
	 ('Pastry - Banana Tea Loaf'),
	 ('Pastry - Carrot Muffin - Mini'),
	 ('Pastry - Cheese Baked Scones'),
	 ('Pastry - Choclate Baked'),
	 ('Pastry - Chocolate Chip Muffin');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pastry - Chocolate Marble Tea'),
	 ('Pastry - Key Limepoppy Seed Tea'),
	 ('Pastry - Lemon Danish - Mini'),
	 ('Pastry - Mini French Pastries'),
	 ('Pastry - Plain Baked Croissant'),
	 ('Pastry - Raisin Muffin - Mini'),
	 ('Pastry - Trippleberry Muffin - Mini'),
	 ('Pate - Cognac'),
	 ('Pate - Liver'),
	 ('Pate - Peppercorn');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pate Pans Yellow'),
	 ('Pea - Snow'),
	 ('Peach - Fresh'),
	 ('Peach - Halves'),
	 ('Pear - Asian'),
	 ('Pear - Halves'),
	 ('Pear - Packum'),
	 ('Pear - Prickly'),
	 ('Pears - Anjou'),
	 ('Pears - Bosc');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pears - Fiorelle'),
	 ('Peas - Frozen'),
	 ('Peas - Pigeon,Dry'),
	 ('Peas Snow'),
	 ('Pecan Raisin - Tarts'),
	 ('Pectin'),
	 ('Pepper - Black,Crushed'),
	 ('Pepper - Black,Ground'),
	 ('Pepper - Black,Whole'),
	 ('Pepper - Chili Powder');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pepper - Chilli Seeds Mild'),
	 ('Pepper - Chillies,Crushed'),
	 ('Pepper - Chipotle,Canned'),
	 ('Pepper - Cubanelle'),
	 ('Pepper - Green'),
	 ('Pepper - Green Thai'),
	 ('Pepper - Green,Chili'),
	 ('Pepper - Gypsy Pepper'),
	 ('Pepper - Jalapeno'),
	 ('Pepper - Julienne,Frozen');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pepper - Orange'),
	 ('Pepper - Pablano'),
	 ('Pepper - Paprika,Hungarian'),
	 ('Pepper - Red Bell'),
	 ('Pepper - Red Chili'),
	 ('Pepper - Red Thai'),
	 ('Pepper - Red,Finger Hot'),
	 ('Pepper - Roasted Red'),
	 ('Pepper - Scotch Bonnet'),
	 ('Pepper - Sorrano');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pepper - White,Ground'),
	 ('Pepper - White,Whole'),
	 ('Pepper - Yellow Bell'),
	 ('Pepper Squash'),
	 ('Peppercorns - Green'),
	 ('Peppercorns - Pink'),
	 ('Pepperoni Slices'),
	 ('Pepsi - 600ml'),
	 ('Pepsi - Diet,355 Ml'),
	 ('Pepsi,355 Ml');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pernod'),
	 ('Persimmons'),
	 ('Pesto - Primerba,Paste'),
	 ('Petit Baguette'),
	 ('Petite Baguette'),
	 ('Pheasants - Whole'),
	 ('Pickerel - Fillets'),
	 ('Pickle - Dill'),
	 ('Pickles - Gherkins'),
	 ('Pie Box - Cello Window 2.5');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pie Filling - Apple'),
	 ('Pie Filling - Cherry'),
	 ('Pie Filling - Pumpkin'),
	 ('Pie Pecan'),
	 ('Pie Shell - 5'),
	 ('Pie Shell - 9'),
	 ('Pie Shells 10'),
	 ('Pike - Frozen Fillet'),
	 ('Pimento - Canned'),
	 ('Pineapple - Canned,Rings');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pineapple - Golden'),
	 ('Pineapple - Regular'),
	 ('Piping - Bags Quizna'),
	 ('Piping Jelly - All Colours'),
	 ('Pizza Pizza Dough'),
	 ('Placemat - Scallop,White'),
	 ('Plaintain'),
	 ('Plastic Arrow Stir Stick'),
	 ('Plastic Wrap'),
	 ('Plasticforkblack');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Plasticknivesblack'),
	 ('Plasticspoonblack'),
	 ('Plate - Foam,Bread And Butter'),
	 ('Plate Foam Laminated 9in Blk'),
	 ('Plate Pie Foil'),
	 ('Plums - Red'),
	 ('Pomegranates'),
	 ('Pomello'),
	 ('Pop - Club Soda Can'),
	 ('Pop Shoppe Cream Soda');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Poppy Seed'),
	 ('Pork - Back Ribs'),
	 ('Pork - Back,Long Cut,Boneless'),
	 ('Pork - Back,Short Cut,Boneless'),
	 ('Pork - Backfat'),
	 ('Pork - Backs - Boneless'),
	 ('Pork - Bacon Cooked Slcd'),
	 ('Pork - Bacon,Sliced'),
	 ('Pork - Bacon,back Peameal'),
	 ('Pork - Bones');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pork - Caul Fat'),
	 ('Pork - Chop,Frenched'),
	 ('Pork - European Side Bacon'),
	 ('Pork - Hock And Feet Attached'),
	 ('Pork - Inside'),
	 ('Pork - Kidney'),
	 ('Pork - Liver'),
	 ('Pork - Loin,Bone - In'),
	 ('Pork - Loin,Boneless'),
	 ('Pork - Loin,Center Cut');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pork - Sausage,Medium'),
	 ('Pork - Shoulder'),
	 ('Pork - Side Ribs'),
	 ('Pork - Smoked Back Bacon'),
	 ('Pork - Smoked Kassler'),
	 ('Pork - Suckling Pig'),
	 ('Pork - Tenderloin,Fresh'),
	 ('Pork - Tenderloin,Frozen'),
	 ('Pork Casing'),
	 ('Pork Ham Prager');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pork Loin Bine - In Frenched'),
	 ('Pork Loin Cutlets'),
	 ('Pork Salted Bellies'),
	 ('Port - 74 Brights'),
	 ('Potato - Sweet'),
	 ('Potatoes - Fingerling 4 Oz'),
	 ('Potatoes - Idaho 100 Count'),
	 ('Potatoes - Idaho 80 Count'),
	 ('Potatoes - Instant,Mashed'),
	 ('Potatoes - Mini Red');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Potatoes - Parissienne'),
	 ('Potatoes - Peeled'),
	 ('Potatoes - Pei 10 Oz'),
	 ('Potatoes - Purple,Organic'),
	 ('Potatoes - Yukon Gold 5 Oz'),
	 ('Praline Paste'),
	 ('Propel Sport Drink'),
	 ('Prunes - Pitted'),
	 ('Puff Pastry - Sheets'),
	 ('Puff Pastry - Slab');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Pumpkin'),
	 ('Pumpkin - Seed'),
	 ('Pur Source'),
	 ('Pur Value'),
	 ('Puree - Blackcurrant'),
	 ('Puree - Guava'),
	 ('Puree - Kiwi'),
	 ('Puree - Mocha'),
	 ('Puree - Pear'),
	 ('Puree - Strawberry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Quail - Eggs,Fresh'),
	 ('Quail - Jumbo'),
	 ('Quail - Jumbo Boneless'),
	 ('Quail - Whole,Bone - In'),
	 ('Quail Eggs - Canned'),
	 ('Quiche Assorted'),
	 ('Rabbit - Frozen'),
	 ('Rabbit - Saddles'),
	 ('Rabbit - Whole'),
	 ('Radish');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Radish - Black,Winter,Organic'),
	 ('Radish - Pickled'),
	 ('Raisin - Dark'),
	 ('Raisin - Golden'),
	 ('Rambutan'),
	 ('Ranchero - Primerba,Paste'),
	 ('Rappini - Andy Boy'),
	 ('Raspberries - Fresh'),
	 ('Raspberries - Frozen'),
	 ('Red Currant Jelly');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Red Currants'),
	 ('Red Pepper Paste'),
	 ('Red Snapper - Fillet,Skin On'),
	 ('Red Snapper - Fresh,Whole'),
	 ('Remy Red'),
	 ('Remy Red Berry Infusion'),
	 ('Rhubarb'),
	 ('Rice - 7 Grain Blend'),
	 ('Rice - Aborio'),
	 ('Rice - Brown');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Rice - Long Grain'),
	 ('Rice - Sushi'),
	 ('Rice - Wild'),
	 ('Rice Pilaf,Dry,package'),
	 ('Roe - Flying Fish'),
	 ('Roe - Lump Fish,Black'),
	 ('Roe - Lump Fish,Red'),
	 ('Roe - White Fish'),
	 ('Rolled Oats'),
	 ('Rootbeer');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Rosemary - Dry'),
	 ('Rosemary - Fresh'),
	 ('Rosemary - Primerba,Paste'),
	 ('Rum - Dark,Bacardi,Black'),
	 ('Rum - Light,Captain Morgan'),
	 ('Rum - Spiced,Captain Morgan'),
	 ('Russian Prince'),
	 ('Rye Special Old'),
	 ('Sachet'),
	 ('Sage - Fresh');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sage - Rubbed'),
	 ('Sage Derby'),
	 ('Sage Ground Wiberg'),
	 ('Salad Dressing'),
	 ('Salami - Genova'),
	 ('Salmon - Atlantic,No Skin'),
	 ('Salmon - Atlantic,Skin On'),
	 ('Salmon - Canned'),
	 ('Salmon - Fillets'),
	 ('Salmon - Smoked,Sliced');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Salmon - Sockeye Raw'),
	 ('Salmon - Whole,4 - 6 Pounds'),
	 ('Salmon Atl.whole 8 - 10 Lb'),
	 ('Salmon Steak - Cohoe 6 Oz'),
	 ('Salmon Steak - Cohoe 8 Oz'),
	 ('Salsify,Organic'),
	 ('Salt - Celery'),
	 ('Salt - Kosher'),
	 ('Salt - Rock,Course'),
	 ('Salt - Sea');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Salt - Seasoned'),
	 ('Salt - Table'),
	 ('Sambuca - Opal Nera'),
	 ('Sambuca - Ramazzotti'),
	 ('Sambuca Cream'),
	 ('Samosa - Veg'),
	 ('Sandwich Wrap'),
	 ('Sansho Powder'),
	 ('Sauce - Alfredo'),
	 ('Sauce - Balsamic Viniagrette');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sauce - Bernaise,Mix'),
	 ('Sauce - Black Current,Dry Mix'),
	 ('Sauce - Demi Glace'),
	 ('Sauce - Fish 25 Ozf Bottle'),
	 ('Sauce - Gravy,Au Jus,Mix'),
	 ('Sauce - Hoisin'),
	 ('Sauce - Hollandaise'),
	 ('Sauce - Marinara'),
	 ('Sauce - Plum'),
	 ('Sauce - Ranch Dressing');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sauce - Roasted Red Pepper'),
	 ('Sauce - Rosee'),
	 ('Sauce - Salsa'),
	 ('Sauce - Sesame Thai Dressing'),
	 ('Sauce - Soy Low Sodium - 3.87l'),
	 ('Sauce - Soya,Dark'),
	 ('Sauce - Soya,Light'),
	 ('Sauce - Thousand Island'),
	 ('Sauce - Vodka Blush'),
	 ('Sauce - White,Mix');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sauce Bbq Smokey'),
	 ('Sauce Tomato Pouch'),
	 ('Sauerkraut'),
	 ('Sausage - Andouille'),
	 ('Sausage - Blood Pudding'),
	 ('Sausage - Breakfast'),
	 ('Sausage - Chorizo'),
	 ('Sausage - Liver'),
	 ('Sausage - Meat'),
	 ('Savory');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Scallop - St. Jaques'),
	 ('Scallops - 10/20'),
	 ('Scallops - 20/30'),
	 ('Scallops - In Shell'),
	 ('Scallops - Live In Shell'),
	 ('Scallops - U - 10'),
	 ('Scampi Tail'),
	 ('Schnappes - Peach,Walkers'),
	 ('Schnappes Peppermint - Walker'),
	 ('Scotch - Queen Anne');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Scrubbie - Scotchbrite Hand Pad'),
	 ('Sea Bass - Fillets'),
	 ('Sea Bass - Whole'),
	 ('Sea Urchin'),
	 ('Seabream Whole Farmed'),
	 ('Seaweed Green Sheets'),
	 ('Seedlings - Buckwheat,Organic'),
	 ('Seedlings - Clamshell'),
	 ('Seedlings - Mix,Organic'),
	 ('Sesame Seed');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sesame Seed Black'),
	 ('Shallots'),
	 ('Shark - Loin'),
	 ('Sherbet - Raspberry'),
	 ('Sherry - Dry'),
	 ('Shichimi Togarashi Peppeers'),
	 ('Shiratamako - Rice Flour'),
	 ('Shopper Bag - S - 4'),
	 ('Shortbread - Cookie Crumbs'),
	 ('Shrimp - 100 / 200 Cold Water');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Shrimp - 150 - 250'),
	 ('Shrimp - 16 - 20 Cooked,Peeled'),
	 ('Shrimp - 16/20,Peeled Deviened'),
	 ('Shrimp - 21/25,Peel And Deviened'),
	 ('Shrimp - 31/40'),
	 ('Shrimp - Baby,Cold Water'),
	 ('Shrimp - Baby,Warm Water'),
	 ('Shrimp - Black Tiger 13/15'),
	 ('Shrimp - Black Tiger 16/20'),
	 ('Shrimp - Black Tiger 26/30');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Shrimp - Black Tiger 6 - 8'),
	 ('Shrimp - Black Tiger 8 - 12'),
	 ('Shrimp - Prawn'),
	 ('Shrimp - Tiger 21/25'),
	 ('Shrimp,Dried,Small / Lb'),
	 ('Silicone Paper 16.5x24'),
	 ('Skewers - Bamboo'),
	 ('Skirt - 24 Foot'),
	 ('Skirt - 29 Foot'),
	 ('Sloe Gin - Mcguinness');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Slt - Individual Portions'),
	 ('Smirnoff Green Apple Twist'),
	 ('Smoked Paprika'),
	 ('Smoked Tongue'),
	 ('Snails - Large Canned'),
	 ('Snapple - Iced Tea Peach'),
	 ('Snapple - Mango Maddness'),
	 ('Snapple Lemon Tea'),
	 ('Snapple Raspberry Tea'),
	 ('Soap - Hand Soap');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soap - Pine Sol Floor Cleaner'),
	 ('Sobe - Berry Energy'),
	 ('Sobe - Green Tea'),
	 ('Sobe - Liz Blizz'),
	 ('Sobe - Lizard Fuel'),
	 ('Sobe - Orange Carrot'),
	 ('Soda Water - Club Soda,355 Ml'),
	 ('Soho Lychee Liqueur'),
	 ('Sole - Dover,Whole,Fresh'),
	 ('Sole - Fillet');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sole - Iqf'),
	 ('Sorrel - Fresh'),
	 ('Soup - Base Broth Beef'),
	 ('Soup - Base Broth Chix'),
	 ('Soup - Beef Conomme,Dry'),
	 ('Soup - Beef,Base Mix'),
	 ('Soup - Boston Clam Chowder'),
	 ('Soup - Campbells'),
	 ('Soup - Campbells - Chicken Noodle'),
	 ('Soup - Campbells - Tomato');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soup - Campbells Asian Noodle'),
	 ('Soup - Campbells Bean Medley'),
	 ('Soup - Campbells Beef Noodle'),
	 ('Soup - Campbells Beef Stew'),
	 ('Soup - Campbells Beef Strogonoff'),
	 ('Soup - Campbells Broccoli'),
	 ('Soup - Campbells Chicken'),
	 ('Soup - Campbells Chili Veg'),
	 ('Soup - Campbells Mac N Cheese'),
	 ('Soup - Campbells Mushroom');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soup - Campbells Pasta Fagioli'),
	 ('Soup - Campbells Tomato Ravioli'),
	 ('Soup - Campbells,Beef Barley'),
	 ('Soup - Campbells,Chix Gumbo'),
	 ('Soup - Campbells,Cream Of'),
	 ('Soup - Campbells,Creamy'),
	 ('Soup - Campbells,Lentil'),
	 ('Soup - Campbells,Minestrone'),
	 ('Soup - Campbells,Spinach Crm'),
	 ('Soup - Campbellschix Stew');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soup - Canadian Pea,Dry Mix'),
	 ('Soup - Clam Chowder,Dry Mix'),
	 ('Soup - Cream Of Broccoli'),
	 ('Soup - Cream Of Broccoli,Dry'),
	 ('Soup - Cream Of Potato / Leek'),
	 ('Soup - French Can Pea'),
	 ('Soup - French Onion,Dry'),
	 ('Soup - Knorr,Chicken Gumbo'),
	 ('Soup - Knorr,Chicken Noodle'),
	 ('Soup - Knorr,Classic Can. Chili');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soup - Knorr,Country Bean'),
	 ('Soup - Knorr,French Onion'),
	 ('Soup - Knorr,Ministrone'),
	 ('Soup - Knorr,Veg / Beef'),
	 ('Soup - Tomato Mush. Florentine'),
	 ('Soup - Verve - Chipotle Chicken'),
	 ('Soup Bowl Clear 8oz92008'),
	 ('Soup Campbells'),
	 ('Soup Campbells - Italian Wedding'),
	 ('Soup Campbells - Tomato Bisque');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Soup Campbells Mexicali Tortilla'),
	 ('Soup Campbells Split Pea And Ham'),
	 ('Soup Campbells Turkey Veg.'),
	 ('Soup Knorr Chili With Beans'),
	 ('Soup V8 Roasted Red Pepper'),
	 ('Soupcontfoam16oz 116con'),
	 ('Soupfoamcont12oz 112con'),
	 ('Sour Cream'),
	 ('Sour Puss - Tangerine'),
	 ('Sour Puss Raspberry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sour Puss Sour Apple'),
	 ('Southern Comfort'),
	 ('Spaghetti Squash'),
	 ('Sparkling Wine - Rose,Freixenet'),
	 ('Spic And Span All Purpose'),
	 ('Spice - Chili Powder Mexican'),
	 ('Spice - Greek 1 Step'),
	 ('Spice - Montreal Steak Spice'),
	 ('Spice - Onion Powder Granulated'),
	 ('Spice - Paprika');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Spice - Pepper Portions'),
	 ('Spinach - Baby'),
	 ('Spinach - Frozen'),
	 ('Spinach - Packaged'),
	 ('Spinach - Spinach Leaf'),
	 ('Sping Loaded Cup Dispenser'),
	 ('Split Peas - Green,Dry'),
	 ('Split Peas - Yellow,Dry'),
	 ('Sponge Cake Mix - Vanilla'),
	 ('Spring Roll Veg Mini');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sprite - 355 Ml'),
	 ('Sprite,Diet - 355ml'),
	 ('Sprouts - Baby Pea Tendrils'),
	 ('Sprouts - Bean'),
	 ('Sprouts - Brussel'),
	 ('Sprouts - China Rose'),
	 ('Sprouts - Corn'),
	 ('Sprouts - Onion'),
	 ('Sprouts - Pea'),
	 ('Sprouts - Peppercress');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sprouts Dikon'),
	 ('Sproutsmustard Cress'),
	 ('Squash - Acorn'),
	 ('Squash - Butternut'),
	 ('Squash - Pattypan,Yellow'),
	 ('Squash - Sunburst'),
	 ('Squeeze Bottle'),
	 ('Squid - Breaded'),
	 ('Squid - U - 10 Thailand'),
	 ('Squid - U 5');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Squid Ink'),
	 ('Squid U5 - Thailand'),
	 ('Stainless Steel Cleaner Vision'),
	 ('Star Fruit'),
	 ('Steam Pan Full Lid'),
	 ('Steamers White'),
	 ('Steampan - Foil'),
	 ('Steampan - Half Size Shallow'),
	 ('Steampan - Lid For Half Size'),
	 ('Steampan Lid');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Steel Wool'),
	 ('Steel Wool S.o.s'),
	 ('Sterno - Chafing Dish Fuel'),
	 ('Stock - Chicken,White'),
	 ('Stock - Fish'),
	 ('Stock - Veal,Brown'),
	 ('Stock - Veal,White'),
	 ('Straw - Regular'),
	 ('Strawberries'),
	 ('Strawberries - California');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Straws - Cocktale'),
	 ('Sugar - Brown'),
	 ('Sugar - Brown,Individual'),
	 ('Sugar - Crumb'),
	 ('Sugar - Cubes'),
	 ('Sugar - Fine'),
	 ('Sugar - Icing'),
	 ('Sugar - Individual Portions'),
	 ('Sugar - Invert'),
	 ('Sugar - Monocystal / Rock');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Sugar - Palm'),
	 ('Sugar - Splenda Sweetener'),
	 ('Sugar - Sweet N Low,Individual'),
	 ('Sugar - White Packet'),
	 ('Sugar Thermometer'),
	 ('Sultanas'),
	 ('Sun - Dried Tomatoes'),
	 ('Sunflower Seed Raw'),
	 ('Sweet Pea Sprouts'),
	 ('Swiss Chard');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Swiss Chard - Red'),
	 ('Sword Pick Asst'),
	 ('Swordfish Loin Portions'),
	 ('Syrup - Chocolate'),
	 ('Syrup - Golden,Lyles'),
	 ('Syrup - Monin - Blue Curacao'),
	 ('Syrup - Monin - Granny Smith'),
	 ('Syrup - Monin - Passion Fruit'),
	 ('Syrup - Monin,Amaretta'),
	 ('Syrup - Monin,Irish Cream');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Syrup - Monin,Swiss Choclate'),
	 ('Syrup - Pancake'),
	 ('Tabasco Sauce,2 Oz'),
	 ('Table Cloth 120 Round White'),
	 ('Table Cloth 53x53 White'),
	 ('Table Cloth 53x69 White'),
	 ('Table Cloth 54x54 White'),
	 ('Table Cloth 54x72 Colour'),
	 ('Table Cloth 54x72 White'),
	 ('Table Cloth 62x114 Colour');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Table Cloth 62x120 Colour'),
	 ('Table Cloth 62x120 White'),
	 ('Table Cloth 72x144 White'),
	 ('Table Cloth 81x81 Colour'),
	 ('Table Cloth 81x81 White'),
	 ('Table Cloth 90x90 Colour'),
	 ('Table Cloth 90x90 White'),
	 ('Table Cloth 91x91 Colour'),
	 ('Tahini Paste'),
	 ('Tamarillo');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tamarind Paste'),
	 ('Tandoori Curry Paste'),
	 ('Taro Leaves'),
	 ('Taro Root'),
	 ('Tarragon - Fresh'),
	 ('Tarragon - Primerba,Paste'),
	 ('Tart - Butter Plain Squares'),
	 ('Tart - Lemon'),
	 ('Tart - Pecan Butter Squares'),
	 ('Tart - Raisin And Pecan');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tart Shells - Barquettes,Savory'),
	 ('Tart Shells - Savory,2'),
	 ('Tart Shells - Savory,3'),
	 ('Tart Shells - Savory,4'),
	 ('Tart Shells - Sweet,2'),
	 ('Tart Shells - Sweet,3'),
	 ('Tart Shells - Sweet,4'),
	 ('Tarts Assorted'),
	 ('Tea - Black Currant'),
	 ('Tea - Camomele');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tea - Darjeeling,Azzura'),
	 ('Tea - Decaf 1 Cup'),
	 ('Tea - Decaf Lipton'),
	 ('Tea - English Breakfast'),
	 ('Tea - Grapefruit Green Tea'),
	 ('Tea - Green'),
	 ('Tea - Herbal I Love Lemon'),
	 ('Tea - Herbal Orange Spice'),
	 ('Tea - Honey Green Tea'),
	 ('Tea - Jasmin Green');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tea - Lemon Green Tea'),
	 ('Tea - Lemon Scented'),
	 ('Tea - Mint'),
	 ('Tea - Orange Pekoe'),
	 ('Tea - Vanilla Chai'),
	 ('Tea Peppermint'),
	 ('Temperature Recording Station'),
	 ('Tendrils - Baby Pea,Organic'),
	 ('Tequila - Sauza Silver'),
	 ('Tequila Rose Cream Liquor');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Teriyaki Sauce'),
	 ('The Pop Shoppe - Black Cherry'),
	 ('The Pop Shoppe - Cream Soda'),
	 ('The Pop Shoppe - Grape'),
	 ('The Pop Shoppe - Lime Rickey'),
	 ('The Pop Shoppe - Root Beer'),
	 ('The Pop Shoppe Pinapple'),
	 ('Thermometer Digital'),
	 ('Thyme - Dried'),
	 ('Tilapia - Fillets');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Toamtoes 6x7 Select'),
	 ('Tobasco Sauce'),
	 ('Tofu - Firm'),
	 ('Tofu - Soft'),
	 ('Tomatillo'),
	 ('Tomato - Peeled Italian Canned'),
	 ('Tomato - Plum With Basil'),
	 ('Tomato - Tricolor Cherry'),
	 ('Tomato Paste'),
	 ('Tomato Puree');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tomatoes'),
	 ('Tomatoes - Cherry'),
	 ('Tomatoes - Cherry,Yellow'),
	 ('Tomatoes - Diced,Canned'),
	 ('Tomatoes - Grape'),
	 ('Tomatoes - Heirloom'),
	 ('Tomatoes - Hot House'),
	 ('Tomatoes - Orange'),
	 ('Tomatoes - Roma'),
	 ('Tomatoes - Vine Ripe,Red');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tomatoes - Vine Ripe,Yellow'),
	 ('Tomatoes Tear Drop'),
	 ('Tortillas - Flour,10'),
	 ('Tortillas - Flour,12'),
	 ('Tortillas - Flour,8'),
	 ('Towel - Roll White'),
	 ('Towel Dispenser'),
	 ('Towel Multifold'),
	 ('Towels - Paper / Kraft'),
	 ('Transfer Sheets');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tray - 16in Rnd Blk'),
	 ('Tray - Foam,Square 4 - S'),
	 ('Triple Sec - Mcguinness'),
	 ('Trout - Hot Smkd,Dbl Fillet'),
	 ('Trout - Rainbow,Fresh'),
	 ('Trout - Smoked'),
	 ('True - Vue Containers'),
	 ('Trueblue - Blueberry'),
	 ('Trueblue - Blueberry 12x473ml'),
	 ('Trueblue - Blueberry Cranberry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Truffle - Peelings'),
	 ('Truffle - Whole Black Peeled'),
	 ('Truffle Cups - Brown'),
	 ('Truffle Cups - Red'),
	 ('Truffle Cups - White Paper'),
	 ('Truffle Cups Green'),
	 ('Truffle Paste'),
	 ('Truffle Shells - Semi - Sweet'),
	 ('Truffle Shells - White Chocolate'),
	 ('Tumeric');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Tuna - Bluefin'),
	 ('Tuna - Fresh'),
	 ('Tuna - Loin'),
	 ('Tuna - Salad Premix'),
	 ('Tuna - Sushi Grade'),
	 ('Tuna - Yellowfin'),
	 ('Turkey - Breast,Boneless Sk On'),
	 ('Turkey - Breast,Double'),
	 ('Turkey - Breast,Smoked'),
	 ('Turkey - Ground. Lean');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Turkey - Oven Roast Breast'),
	 ('Turkey - Whole,Fresh'),
	 ('Turkey Leg With Drum And Thigh'),
	 ('Turkey Tenderloin Frozen'),
	 ('Turnip - Mini'),
	 ('Turnip - Wax'),
	 ('Turnip - White'),
	 ('Turnip - White,Organic'),
	 ('Urban Zen Drinks'),
	 ('V8 - Berry Blend');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('V8 - Tropical Blend'),
	 ('V8 - Vegetable Cocktail'),
	 ('V8 Pet'),
	 ('V8 Splash Strawberry Banana'),
	 ('V8 Splash Strawberry Kiwi'),
	 ('Vaccum Bag - 14x20'),
	 ('Vaccum Bag 10x13'),
	 ('Veal - Bones'),
	 ('Veal - Brisket,Provimi,bnls'),
	 ('Veal - Chops,Split,Frenched');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Veal - Eye Of Round'),
	 ('Veal - Ground'),
	 ('Veal - Heart'),
	 ('Veal - Inside'),
	 ('Veal - Inside Round / Top,Lean'),
	 ('Veal - Inside,Choice'),
	 ('Veal - Insides Provini'),
	 ('Veal - Insides,Grains'),
	 ('Veal - Kidney'),
	 ('Veal - Knuckle');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Veal - Leg'),
	 ('Veal - Leg,Provimi - 50 Lb Max'),
	 ('Veal - Liver'),
	 ('Veal - Loin'),
	 ('Veal - Nuckle'),
	 ('Veal - Osso Bucco'),
	 ('Veal - Provimi Inside'),
	 ('Veal - Round,Eye Of'),
	 ('Veal - Shank,Pieces'),
	 ('Veal - Striploin');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Veal - Sweetbread'),
	 ('Veal - Tenderloin,Untrimmed'),
	 ('Veal Inside - Provimi'),
	 ('Vegetable - Base'),
	 ('Venison - Denver Leg Boneless'),
	 ('Venison - Liver'),
	 ('Venison - Racks Frenched'),
	 ('Venison - Striploin'),
	 ('Vermacelli - Sprinkles,Assorted'),
	 ('Vermouth - Sweet,Cinzano');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Vermouth - White,Cinzano'),
	 ('Versatainer Nc - 888'),
	 ('Vinegar - Balsamic'),
	 ('Vinegar - Balsamic,White'),
	 ('Vinegar - Champagne'),
	 ('Vinegar - Cider'),
	 ('Vinegar - Red Wine'),
	 ('Vinegar - Rice'),
	 ('Vinegar - Sherry'),
	 ('Vinegar - Tarragon');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Vinegar - White'),
	 ('Vinegar - White Wine'),
	 ('Vodka - Hot,Lnferno'),
	 ('Vodka - Moskovskaya'),
	 ('Vodka - Smirnoff'),
	 ('Vol Au Vents'),
	 ('Waffle Stix'),
	 ('Wakami Seaweed'),
	 ('Walkers Special Old Whiskey'),
	 ('Wanton Wrap');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wasabi Paste'),
	 ('Wasabi Powder'),
	 ('Water - Aquafina Vitamin'),
	 ('Water - Evian 355 Ml'),
	 ('Water - Green Tea Refresher'),
	 ('Water - Mineral,Carbonated'),
	 ('Water - Mineral,Natural'),
	 ('Water - Perrier'),
	 ('Water - San Pellegrino'),
	 ('Water - Spring 1.5lit');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Water - Spring Water 500ml'),
	 ('Water Chestnut - Canned'),
	 ('Water,Tap'),
	 ('Watercress'),
	 ('Wheat - Soft Kernal Of Wheat'),
	 ('White Baguette'),
	 ('White Fish - Filets'),
	 ('Whmis - Spray Bottle Trigger'),
	 ('Whmis Spray Bottle Graduated'),
	 ('Wiberg Super Cure');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wild Boar - Tenderloin'),
	 ('Wine - Acient Coast Caberne'),
	 ('Wine - Alicanca Vinho Verde'),
	 ('Wine - Alsace Gewurztraminer'),
	 ('Wine - Alsace Riesling Reserve'),
	 ('Wine - Balbach Riverside'),
	 ('Wine - Barbera Alba Doc 2001'),
	 ('Wine - Barolo Fontanafredda'),
	 ('Wine - Baron De Rothschild'),
	 ('Wine - Barossa Valley Estate');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Beaujolais Villages'),
	 ('Wine - Beringer Founders Estate'),
	 ('Wine - Black Tower Qr'),
	 ('Wine - Blue Nun Qualitatswein'),
	 ('Wine - Cabernet Sauvignon'),
	 ('Wine - Cahors Ac 2000,Clos'),
	 ('Wine - Carmenere Casillero Del'),
	 ('Wine - Casablanca Valley'),
	 ('Wine - Casillero Del Diablo'),
	 ('Wine - Cava Aria Estate Brut');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Cave Springs Dry Riesling'),
	 ('Wine - Chablis 2003 Champs'),
	 ('Wine - Chablis J Moreau Et Fils'),
	 ('Wine - Champagne Brut Veuve'),
	 ('Wine - Charddonnay Errazuriz'),
	 ('Wine - Chardonnay Mondavi'),
	 ('Wine - Chardonnay South'),
	 ('Wine - Chateau Aqueria Tavel'),
	 ('Wine - Chateau Bonnet'),
	 ('Wine - Chateauneuf Du Pape');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Chenin Blanc K.w.v.'),
	 ('Wine - Chianti Classico Riserva'),
	 ('Wine - Clavet Saint Emilion'),
	 ('Wine - Conde De Valdemar'),
	 ('Wine - Coteaux Du Tricastin Ac'),
	 ('Wine - Cotes Du Rhone'),
	 ('Wine - Cotes Du Rhone Parallele'),
	 ('Wine - Cousino Macul Antiguas'),
	 ('Wine - Crozes Hermitage E.'),
	 ('Wine - Delicato Merlot');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Domaine Boyar Royal'),
	 ('Wine - Dubouef Macon - Villages'),
	 ('Wine - Ej Gallo Sonoma'),
	 ('Wine - Fat Bastard Merlot'),
	 ('Wine - Fino Tio Pepe Gonzalez'),
	 ('Wine - Fontanafredda Barolo'),
	 ('Wine - Fume Blanc Fetzer'),
	 ('Wine - Gato Negro Cabernet'),
	 ('Wine - George Duboeuf Rose'),
	 ('Wine - German Riesling');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Gewurztraminer Pierre'),
	 ('Wine - Guy Sage Touraine'),
	 ('Wine - Hardys Bankside Shiraz'),
	 ('Wine - Ice Wine'),
	 ('Wine - Jaboulet Cotes Du Rhone'),
	 ('Wine - Jackson Triggs Okonagan'),
	 ('Wine - Jafflin Bourgongone'),
	 ('Wine - Kwv Chenin Blanc South'),
	 ('Wine - Lamancha Do Crianza'),
	 ('Wine - Lou Black Shiraz');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Magnotta - Bel Paese White'),
	 ('Wine - Magnotta - Belpaese'),
	 ('Wine - Magnotta - Cab Franc'),
	 ('Wine - Magnotta - Cab Sauv'),
	 ('Wine - Magnotta - Red,Baco'),
	 ('Wine - Magnotta,Merlot Sr Vqa'),
	 ('Wine - Magnotta,White'),
	 ('Wine - Malbec Trapiche Reserve'),
	 ('Wine - Manischewitz Concord'),
	 ('Wine - Marlbourough Sauv Blanc');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Mas Chicet Rose,Vintage'),
	 ('Wine - Masi Valpolocell'),
	 ('Wine - Merlot Vina Carmen'),
	 ('Wine - Mondavi Coastal Private'),
	 ('Wine - Montecillo Rioja Crianza'),
	 ('Wine - Muscadet Sur Lie'),
	 ('Wine - Niagara,vqa Reisling'),
	 ('Wine - Peller Estates Late'),
	 ('Wine - Penfolds Koonuga Hill'),
	 ('Wine - Periguita Fonseca');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Pinot Grigio Collavini'),
	 ('Wine - Pinot Noir Latour'),
	 ('Wine - Pinot Noir Pond Haddock'),
	 ('Wine - Pinot Noir Stoneleigh'),
	 ('Wine - Piper Heidsieck Brut'),
	 ('Wine - Port Late Bottled Vintage'),
	 ('Wine - Prem Select Charddonany'),
	 ('Wine - Prosecco Valdobiaddene'),
	 ('Wine - Prosecco Valdobienne'),
	 ('Wine - Puligny Montrachet A.');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Red Oakridge Merlot'),
	 ('Wine - Red,Antinori Santa'),
	 ('Wine - Red,Black Opal Shiraz'),
	 ('Wine - Red,Cabernet Merlot'),
	 ('Wine - Red,Cabernet Sauvignon'),
	 ('Wine - Red,Concha Y Toro'),
	 ('Wine - Red,Cooking'),
	 ('Wine - Red,Gallo,Merlot'),
	 ('Wine - Red,Gamay Noir'),
	 ('Wine - Red,Harrow Estates,Cab');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Red,Lurton Merlot De'),
	 ('Wine - Red,Marechal Foch'),
	 ('Wine - Red,Metus Rose'),
	 ('Wine - Red,Mouton Cadet'),
	 ('Wine - Red,Pelee Island Merlot'),
	 ('Wine - Red,Pinot Noir,Chateau'),
	 ('Wine - Red,Wolf Blass,Yellow'),
	 ('Wine - Redchard Merritt'),
	 ('Wine - Rhine Riesling Wolf Blass'),
	 ('Wine - Riesling Alsace Ac 2001');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Rioja Campo Viejo'),
	 ('Wine - Rosso Del Veronese Igt'),
	 ('Wine - Rosso Toscano Igt'),
	 ('Wine - Rubyport'),
	 ('Wine - Ruffino Chianti'),
	 ('Wine - Ruffino Chianti Classico'),
	 ('Wine - Saint - Bris 2002,Sauv'),
	 ('Wine - Saint Emilion Calvet'),
	 ('Wine - Sake'),
	 ('Wine - Sauvignon Blanc');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Sauvignon Blanc Oyster'),
	 ('Wine - Savigny - Les - Beaune'),
	 ('Wine - Sawmill Creek Autumn'),
	 ('Wine - Segura Viudas Aria Brut'),
	 ('Wine - Semi Dry Riesling Vineland'),
	 ('Wine - Sherry Dry Sack,William'),
	 ('Wine - Shiraz South Eastern'),
	 ('Wine - Shiraz Wolf Blass Premium'),
	 ('Wine - Sicilia Igt Nero Avola'),
	 ('Wine - Soave Folonari');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Sogrape Mateus Rose'),
	 ('Wine - Spumante Bambino White'),
	 ('Wine - Stoneliegh Sauvignon'),
	 ('Wine - Taylors Reserve'),
	 ('Wine - Tio Pepe Sherry Fino'),
	 ('Wine - Toasted Head'),
	 ('Wine - Touraine Azay - Le - Rideau'),
	 ('Wine - Tribal Sauvignon'),
	 ('Wine - Trimbach Pinot Blanc'),
	 ('Wine - Two Oceans Cabernet');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - Two Oceans Sauvignon'),
	 ('Wine - Valpolicella Masi'),
	 ('Wine - Vidal Icewine Magnotta'),
	 ('Wine - Vineland Estate Semi - Dry'),
	 ('Wine - Vouvray Cuvee Domaine'),
	 ('Wine - White Cab Sauv.on'),
	 ('Wine - White,Antinore Orvieto'),
	 ('Wine - White,Chardonnay'),
	 ('Wine - White,Colubia Cresh'),
	 ('Wine - White,Concha Y Toro');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - White,Cooking'),
	 ('Wine - White,Ej'),
	 ('Wine - White,Ej Gallo'),
	 ('Wine - White,French Cross'),
	 ('Wine - White,Gewurtzraminer'),
	 ('Wine - White,Lindemans Bin 95'),
	 ('Wine - White,Mosel Gold'),
	 ('Wine - White,Pinot Grigio'),
	 ('Wine - White,Riesling,Henry Of'),
	 ('Wine - White,Riesling,Semi - Dry');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Wine - White,Schroder And Schyl'),
	 ('Wine - Winzer Krems Gruner'),
	 ('Wine - Wyndham Estate Bin 777'),
	 ('Wine - Zinfandel California 2002'),
	 ('Wine - Zinfandel Rosenblum'),
	 ('Wine - Zonnebloem Pinotage'),
	 ('Wine La Vielle Ferme Cote Du'),
	 ('Wonton Wrappers'),
	 ('Wood Chips - Regular'),
	 ('Wooden Mop Handle');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Worcestershire Sauce'),
	 ('Yeast - Fresh,Fleischman'),
	 ('Yeast Dry - Fermipan'),
	 ('Yeast Dry - Fleischman'),
	 ('Yoghurt Tubes'),
	 ('Yogurt - Banana,175 Gr'),
	 ('Yogurt - Blueberry,175 Gr'),
	 ('Yogurt - Cherry,175 Gr'),
	 ('Yogurt - French Vanilla'),
	 ('Yogurt - Peach,175 Gr');
INSERT INTO public.dimensao_produto (produto) VALUES
	 ('Yogurt - Plain'),
	 ('Yogurt - Raspberry,175 Gr'),
	 ('Yogurt - Strawberry,175 Gr'),
	 ('Yokaline'),
	 ('Yoplait - Strawbrasp Peac'),
	 ('Yoplait Drink'),
	 ('Yukon Jack'),
	 ('Zucchini - Green'),
	 ('Zucchini - Mini,Green'),
	 ('Zucchini - Yellow');